name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # schedule:
  #     - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # - name: Set Chrome Driver
    #   run: |
    #     choco install googlechrome
    #     curl -LO https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_win32.zip
    #     unzip chromedriver_win32.zip
    #     move chromedriver.exe C:\chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Run tests
      run: |
        robot tests/